drop index idx_project_resources_id;
drop index idx_project_resources_resource_uuid;
drop index idx_project_resources_project_uuid;
drop index idx_project_resources_role;
drop index idx_project_resources_created_at;
drop index idx_project_resources_created_by;
drop index idx_project_resources_updated_at;
drop index idx_project_resources_updated_by;
