### login
POST {{host}}/hta-gantt/v1.0/login
Content-Type: application/json

{
  "user_name": "admin",
  "password": "3939889"
}

### verify
POST {{host}}/hta-gantt/v1.0/verify
Content-Type: application/json

{
  "user_name": "admin",
  "passcode": "117805"
}

> {% client.global.set("accessToken", response.body.body.access_token); %}

### GetByList
GET {{host}}/hta-gantt/v1.0/companies?page=1&limit=20
Accept: application/json
Authorization: Bearer {{accessToken}}

### GetByListNoPagination
GET {{host}}/hta-gantt/v1.0/companies/no-pagination
Accept: application/json
Authorization: Bearer {{accessToken}}

### GetBySingle
GET {{host}}/hta-gantt/v1.0/companies/9db74c35-804e-48f2-910c-6bf80494cbf0
Accept: application/json
Authorization: Bearer {{accessToken}}

### Create
POST {{host}}/hta-gantt/v1.0/companies
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "domain": "pm.hta365.net",
  "name": "production",
  "remarks": "正式站"
}

### Update
PATCH {{host}}/hta-gantt/v1.0/companies/de0a714b-a332-4a32-890b-e10036ffad01
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "pre-production"
}

### Delete
DELETE {{host}}/hta-gantt/v1.0/companies/f01fabb7-bce5-44ab-a20f-aa78589b5409
Accept: application/json
Authorization: Bearer {{accessToken}}
