### login
POST {{host}}/hta-gantt/v1.0/login
Content-Type: application/json

{
  "user_name": "hsxxnil",
  "password": "12345"
}

### verify
POST {{host}}/hta-gantt/v1.0/verify
Content-Type: application/json

{
  "user_name": "hsxxnil",
  "passcode": "293512"
}

> {% client.global.set("refreshToken", response.body.body.refresh_token); %}

### refresh
POST {{host}}/hta-gantt/v1.0/refresh
Content-Type: application/json

{
  "refresh_token": "{{refreshToken}}"
}

### forget
POST {{host}}/hta-gantt/v1.0/forget-password
Content-Type: application/json

{
  "email": "REMOVED",
  "domain": "localhost",
  "port": "4200"
}

### register
POST {{host}}/hta-gantt/v1.0/register
Content-Type: application/json

{
  "user_name": "hsxxnil",
  "password": "12345",
  "email": "",
  "domain": "localhost",
  "port": "4200"
}

