### login
POST {{host}}/hta-gantt/v1.0/login
Content-Type: application/json

{
  "user_name": "hsxxnil",
  "password": "a1111111",
  "change_to": 1
}

### verify
POST {{host}}/hta-gantt/v1.0/verify
Content-Type: application/json

{
  "user_name": "woni",
  "passcode": "457533"
}

> {% client.global.set("refreshToken", response.body.body.refresh_token); %}

### refresh
POST {{host}}/hta-gantt/v1.0/refresh
Content-Type: application/json

{
  "refresh_token": "{{refreshToken}}"
}

### forget
POST {{host}}/hta-gantt/v1.0/forget-password
Content-Type: application/json

{
  "email": "REMOVED",
  "domain": "localhost",
  "port": "4200"
}

### register
POST {{host}}/hta-gantt/v1.0/register
Content-Type: application/json

{
  "user_name": "test",
  "password": "REMOVED",
  "email": "abc@gmail.com",
  "domain": "localhost",
  "port": "4200"
}

