### login
POST {{host}}/hta-gantt/v1.0/login
Content-Type: application/json

{
  "user_name": "woni",
  "password": "12345"
}

### verify
POST {{host}}/hta-gantt/v1.0/verify
Content-Type: application/json

{
  "user_name": "admin",
  "passcode": "623274"
}

> {% client.global.set("accessToken", response.body.body.access_token); %}

### GetByList
POST {{host}}/hta-gantt/v1.0/projects/list?page=1&limit=20
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "filter": {
    "status": ["已終止"],
    "type": "",
    "client": "",
    "project_name": "",
    "manager": "",
    "code": ""
  }
}

### GetByListNoPagination
GET {{host}}/hta-gantt/v1.0/projects/no-pagination
Accept: application/json
Authorization: Bearer {{accessToken}}

### GetBySingle
GET {{host}}/hta-gantt/v1.0/projects/ed76ede3-7956-4d18-a1ed-6d7df3943b77
Accept: application/json
Authorization: Bearer {{accessToken}}

### Create
POST {{host}}/hta-gantt/v1.0/projects
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "project_name": "test",
  "type": "1a5c6ba3-a97c-4d81-ab44-4755e9d6ae4e",
  "manager": "8b5ca145-665f-4039-b7e1-50ae94dfb5eb",
  "code": "123456"
}

### Update
PATCH {{host}}/hta-gantt/v1.0/projects/f58324b7-99dd-45a0-9036-1954a77138ca
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "project_name": "123",
  "resource": []
}

### Delete
DELETE {{host}}/hta-gantt/v1.0/projects/5e13ee25-536a-40f7-8585-2aea56ba0191
Accept: application/json
