### login
POST {{host}}/hta-gantt/v1.0/login
Content-Type: application/json

{
  "user_name": "hsxxnil",
  "password": "12345"
}

### verify
POST {{host}}/hta-gantt/v1.0/verify
Content-Type: application/json

{
  "user_name": "hsxxnil",
  "passcode": "356307"
}

> {% client.global.set("accessToken", response.body.body.access_token); %}

### GetByProjectUUIDList
POST {{host}}/hta-gantt/v1.0/tasks/get-by-projects
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "filter": {
    "is_milestone": false
  },
  "projects": [
    "095198af-2651-4477-b574-e0f8871390e2"
  ]
}

### GetByListNoPaginationNoSub
GET {{host}}/hta-gantt/v1.0/tasks/no-pagination/no-sub-filter
Accept: application/json
Authorization: Bearer {{accessToken}}

### GetBySingle
GET {{host}}/hta-gantt/v1.0/tasks/ce9180ec-f24f-43fa-b60f-2578d35d725d
Accept: application/json
Authorization: Bearer {{accessToken}}

### Create
POST {{host}}/hta-gantt/v1.0/tasks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "task_name": "Project initiation Sub",
  "start_date": "2023-09-25T00:00:00.000Z",
  "end_date": "2023-09-27T00:00:00.000Z",
  "baseline_start_date": "2020-09-27T00:00:00.000Z",
  "baseline_end_date": "2025-09-25T00:00:00.000Z",
  "project_uuid": "87911984-302b-4085-8539-90fe85487801"
}

### CreateAll
POST {{host}}/hta-gantt/v1.0/tasks/create-all
Content-Type: application/json
Authorization: Bearer {{accessToken}}

[
  {
    "task_name": "Project initiation Sub",
    "start_date": "2023-09-25T00:00:00Z",
    "end_date": "2023-10-31T09:00:00Z",
    "baseline_start_date": "2021-09-27T00:00:00Z",
    "baseline_end_date": "2024-09-25T00:00:00Z",
    "duration": 26,
    "project_uuid": "87911984-302b-4085-8539-90fe85487801"
  },
  {
    "task_name": "Project initiation Sub",
    "start_date": "2023-09-25T00:00:00Z",
    "end_date": "2023-09-27T00:00:00Z",
    "baseline_start_date": "2021-09-27T00:00:00Z",
    "baseline_end_date": "2024-09-25T00:00:00Z",
    "project_uuid": "87911984-302b-4085-8539-90fe85487801"
  },
  {
    "task_name": "未命名任務",
    "project_uuid": "87911984-302b-4085-8539-90fe85487801"
  },
  {
    "task_name": "未命名任務",
    "project_uuid": "87911984-302b-4085-8539-90fe85487801"
  }
]

### Update
PATCH {{host}}/hta-gantt/v1.0/tasks/40de0b9f-db01-4c70-8878-d1ff8932bbbe
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "task_name": "D"
}

### UpdateAll
PATCH {{host}}/hta-gantt/v1.0/tasks/update-all
Content-Type: application/json
Authorization: Bearer {{accessToken}}

[
  {
  }
]

### Delete
DELETE {{host}}/hta-gantt/v1.0/tasks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "tasks": [
    "f3c4913a-226b-45d9-b631-5fd58bdd68f5",
    "661e155d-3a9f-446b-9a6d-b9f968575988",
    "a97b7389-f74d-42ed-818d-3dc81ea8af56",
    "377cf92c-83c6-44b1-966b-66fce5902041",
    "d5960f2c-d5d0-43d0-bac7-a33cd39fac34"
  ],
  "project_uuid": "c84bfa4f-9b0e-4e2d-a20f-b4936ec12fb0"
}

### Import
POST {{host}}/hta-gantt/v1.0/tasks/import
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "base64": "SUQs5ZCN56ixLOiyoOiyrOS6uizlt6XkvZzlpKks6ZaL5aeL5pel5pyfLOe1kOadn+aXpeacnyzln7rmupbplovlp4vml6Us5Z+65rqW57WQ5p2f5pelLOWfuua6luW3peS9nOWkqSzpgLLluqYoJSks55u45L6d5oCnLOW3peaZguihqCzlpKfntrHnt6jomZ8KMSx0YXNrIDEs5p2OT+iTgSw0IOWkqSwyMDI0LTAxLTAyLDIwMjQtMDEtMDUsMjAyNC0wMS0wMiwyMDI0LTAxLTA1LDTlpKksMCwsLDEKMix0YXNrIDIs5p2OT+iQsSw1IOWkqSwyMDI0LTAxLTA4LDIwMjQtMDEtMTIsMjAyNC0wMS0wOCwyMDI0LTAxLTEyLDXlpKksMCwsLDIKMyx0YXNrIDMs5p6XT+eShyw1IOWkqSwyMDI0LTAxLTE1LDIwMjQtMDEtMTksMjAyNC0wMS0xNSwyMDI0LTAxLTE5LDXlpKksMCwsLDM=",
  "project_uuid": "f4d46b57-3db6-4088-99ae-832f437f2cb0",
  "file_type": 2
}