### login
POST {{host}}/hta-gantt/v1.0/login
Content-Type: application/json

{
  "user_name": "hsxxnil",
  "password": "12345"
}

### verify
POST {{host}}/hta-gantt/v1.0/verify
Content-Type: application/json

{
  "user_name": "hsxxnil",
  "passcode": "639740"
}

> {%
    client.global.set("accessToken", response.body.body.access_token);
%}

### GetByList
POST {{host}}/hta-gantt/v1.0/users/list?page=1&limit=20
Accept: application/json
Authorization: Bearer {{accessToken}}

### GetByListNoPagination
GET {{host}}/hta-gantt/v1.0/users?page=1&limit=20
Accept: application/json
Authorization: Bearer {{accessToken}}

### GetBySingle
GET {{host}}/hta-gantt/v1.0/users/552daa60-f9a6-4d90-9a31-16fcbf7d62e8
Accept: application/json
Authorization: Bearer {{accessToken}}

### GetByCurrent
GET {{host}}/hta-gantt/v1.0/users/current-user
Accept: application/json
Authorization: Bearer {{accessToken}}

### Create
POST {{host}}/hta-gantt/v1.0/users
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "user_name": "kevin_lin",
  "name": "林中庸",
  "password": "12345",
  "email": "REMOVED",
  "role_id": "d56fc184-9441-4396-be6c-d48580650171"
}

### Update
PATCH {{host}}/hta-gantt/v1.0/users/current-user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "password": "12345",
  "old_password": "54321"
}

### Enable
PATCH {{host}}/hta-gantt/v1.0/users/enable/85cee689-bcb2-461f-8b0a-ea6922f1cb07
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "is_enabled": false
}

### EnableByCurrent
PATCH {{host}}/hta-gantt/v1.0/users/enable/current-user
Accept: application/json
Authorization: Bearer REMOVED

### ResetPassword
PATCH {{host}}/hta-gantt/v1.0/users/reset-password/current-user
Content-Type: application/json
Authorization: Bearer REMOVEDREMOVED

{
  "password": "12345"
}

### Delete
DELETE {{host}}/hta-gantt/v1.0/users/fef3c69f-7375-45ed-986f-2b07eabca892
Accept: application/json
Authorization: Bearer {{accessToken}}

### Duplicate
POST {{host}}/hta-gantt/v1.0/users/check-duplicate
Content-Type: application/json

{
  "filter": {
    "user_name": "",
    "email": "REMOVED"
  }
}