### login
POST {{host}}/hta-gantt/v1.0/login
Content-Type: application/json

{
  "user_name": "hsxxnil",
  "password": "12345",
  "domain": "localhost"
}

### verify
POST {{host}}/hta-gantt/v1.0/verify
Content-Type: application/json

{
  "user_name": "hsxxnil",
  "passcode": "728400",
  "domain": "pm.hta365.net"
}

> {% client.global.set("accessToken", response.body.body.access_token); %}

### GetByList
POST {{host}}/hta-gantt/v1.0/users/list?page=1&limit=20
Accept: application/json
Authorization: Bearer {{accessToken}}

### GetByListNoPagination
GET {{host}}/hta-gantt/v1.0/users?page=1&limit=20
Accept: application/json
Authorization: Bearer {{accessToken}}

### GetBySingle
GET {{host}}/hta-gantt/v1.0/users/85cee689-bcb2-461f-8b0a-ea6922f1cb07
Accept: application/json
Authorization: Bearer {{accessToken}}

### GetByCurrent
GET {{host}}/hta-gantt/v1.0/users/current-user
Accept: application/json
Authorization: Bearer {{accessToken}}

### Create
POST {{host}}/hta-gantt/v1.0/users
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "user_name": "kevin_lin",
  "name": "林中庸",
  "password": "12345",
  "email": "Kevin_lin@hta.com.tw",
  "role_id": "d56fc184-9441-4396-be6c-d48580650171",
  "company_id": "d2de3502-bafb-4434-96fa-b191dcfce44d"
}

### Update
PATCH {{host}}/hta-gantt/v1.0/users/current-user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "password": "12345",
  "old_password": "54321"
}

### ResetPassword
PATCH {{host}}/hta-gantt/v1.0/users/reset-password/current-user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSU0EtT0FFUC0yNTYiLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIiwidHlwZSI6IkpXRSIsInppcCI6IkRFRiJ9.R7sM65KxoE1tm5wKjs2r3st6OIZlYVJ9eCuA0Dez80vUmiG6lInER8tWBXpSYC6QsH46h3R9Iz_1Bqpp5OGscFKrm9QVvMQXEvAlym6bRd1RRsz-OyE0i-uSQvJEYvQZX6FA_aQvA51EFAg-dhBTNMZYY4BhlvQIPeVFbWr80KSQmnolbJAiA2dMYNb1F9Swc1Tb6Qjpr-IohLvArO_ogdhdokU5QuQI4BYMt7r-Uo2m5i0LXibuC5VHG0UZW1xNDWd2tp1OnntqDL-EaaunZP__KQ4mmPQ8P6OgATaHiQ2Gzk94hElQFtt7zN9b9Ei7MSCuHzwmbQwmi-mb8shgkg.W0c50itwJ9PxqOI4XA9uBg.ShRc4US4iF11vaCxL6ub1cqzxIA9-1W-jt7RekXNh8OyivIt2oI-uQxC4ySJ6qbgCuwehB6CDkp9CNc8ZERVdcDeg02f57j1yoCYy7vduZqVK28OMMmvrRybfqagMpixf3_3UlnhqtY0958-rIDqmiNaw8lafWkiShnLOPccMx9hsTfBE_P5mbHzPifR25omEXOFaVUlp2zKOgBaDpd02uMja7LwBjetU8sTvjwGnU4.r_ewUHPkOq-B1o3OtuWbrnU9XLtEflM7ryG9jiEVoAc

{
  "password": "12345"
}


### Delete
DELETE {{host}}/hta-gantt/v1.0/users/fef3c69f-7375-45ed-986f-2b07eabca892
Accept: application/json
Authorization: Bearer {{accessToken}}