### login
POST {{host}}/gantt/v1.0/login
Content-Type: application/json

{
  "user_name": "admin",
  "password": "12345"
}

### verify
# @name verify
POST {{host}}/gantt/v1.0/verify
Content-Type: application/json

{
  "user_name": "admin",
  "passcode": "353575"
}

# > {%client.global.set("accessToken", response.body.body.access_token); %}
@accessToken = {{verify.response.body.body.access_token}}

### GetByList
POST {{host}}/gantt/v1.0/users/list?page=1&limit=20
Accept: application/json
Authorization: Bearer {{accessToken}}

### GetByListNoPagination
GET {{host}}/gantt/v1.0/users?page=1&limit=20
Accept: application/json
Authorization: Bearer {{accessToken}}

### GetBySingle
GET {{host}}/gantt/v1.0/users/6b47e0c6-a4b7-418d-9b52-799449a6c58d
Accept: application/json
Authorization: Bearer {{accessToken}}

### GetByCurrent
GET {{host}}/gantt/v1.0/users/current-user
Accept: application/json
Authorization: Bearer {{accessToken}}

### Create
POST {{host}}/gantt/v1.0/users
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "user_name": "kevin_lin",
  "name": "林中庸",
  "password": "12345",
  "email": "REMOVED",
  "role_id": "d56fc184-9441-4396-be6c-d48580650171"
}

### Update
PATCH {{host}}/gantt/v1.0/users/current-user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "affiliations": [
    {
      "dept_id": "39a2d69c-452b-410f-8753-f8a92802c3a2",
      "job_title": "工程師",
      "is_supervisor": false
    },
    {
      "dept_id": "57714348-a870-446d-83d4-0ab5b24309cd",
      "job_title": "工程師",
      "is_supervisor": false
    }
  ]
}

### Enable
PATCH {{host}}/gantt/v1.0/users/enable/85cee689-bcb2-461f-8b0a-ea6922f1cb07
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "is_enabled": false
}

### EnableByCurrent
POST {{host}}/gantt/v1.0/users/enable/current-user
Accept: application/json
Authorization: Bearer REMOVED

### ResetPassword
POST {{host}}/gantt/v1.0/users/reset-password/current-user
Content-Type: application/json
Authorization: Bearer REMOVEDREMOVED

{
  "password": "12345"
}

### Delete
DELETE {{host}}/gantt/v1.0/users/c5fa10ae-c1f9-4840-bb53-254a64068d66
Accept: application/json
Authorization: Bearer {{accessToken}}

### Duplicate
POST {{host}}/gantt/v1.0/users/check-duplicate
Content-Type: application/json

{
  "filter": {
    "user_name": "",
    "email": "REMOVED"
  }
}

### EnableAuthenticator
POST {{host}}/gantt/v1.0/users/authenticator/current-user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "passcode": "060197"
}

### ChangeEmail
POST {{host}}/gantt/v1.0/users/change-email/current-user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "email": "REMOVED",
  "domain": "d.pmip.likbox.com"
}

### VerifyEmail
POST {{host}}/gantt/v1.0/users/verify-email/current-user
Accept: application/json
Authorization: Bearer REMOVED
